# fly.toml app configuration file generated for sleekvim on 2025-02-13T20:15:34-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sleekvim'
primary_region = 'lax'

[build]

[http_service]
  auto_start_machines = true
  auto_stop_machines = false
  force_https = true
  internal_port = 3000
  min_machines_running = 0

[mounts]
  destination = "/data"
  snapshot_retention = 60
  source = "sleekvim_data"

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory = '256mb'
  size = 'shared-cpu-1x'
